apiVersion: skaffold/v2beta5
build:
  artifacts:
  - image: gcr.io/yuwenma-gke-playground/demo-backend
    context: /workspace/src-repo
  cluster:
    namespace: pl
kind: Config
metadata:
  name: backend-config
