apiVersion: skaffold/v2beta5
build:
  artifacts:
  - image: gcr.io/yuwenma-gke-playground/demo-backend
    context: /workspace/src-repo
  cluster:
    pullSecretPath: kaniko-secret.json
    namespace: pl
    serviceAccount: tranf-ksa
kind: Config
metadata:
  name: backend-config
