apiVersion: skaffold/v2beta4
build:
  artifacts:
  - image: gcr.io/yuwenma-gke-playground/demo-backend
  googleCloudBuild:
    projectId: yuwenma-gke-playground
kind: Config
metadata:
  name: backend-config
