apiVersion: skaffold/v2beta5
build:
  artifacts:
  - image: gcr.io/yuwenma-gke-playground/demo-backend
    kaniko: {}
  cluster:
    namespace: pl
    pullSecretPath: kaniko-secret.json
kind: Config
metadata:
  name: backend-config
